### ISSUE TITLE
Still receiving timeout error

### ISSUE THREAD

**Issue by jarigoni** [wchatx/direct-access-py#29]
Using the following code:

```
prod_list = []
    print('Begin DI Pull')
    for ID in GroupedEntityIds:
        
        for row in d2.query(
        'producing-entity-details',
        fields='ApiNo,EntityId,Gas,Liq,ProdDate,ProdMonthNo',
        EntityId='in({})'.format(','.join([str(x) for x in ID])),
        DeletedDate='null',
        proddate='gt(2009-12-01)',
        pagesize=10000):
            prod_list.append(row)
```

Error:

RetryError: HTTPSConnectionPool(host='di-api.drillinginfo.com', port=443): Max retries exceeded with url: /v2/direct-access/producing-entity-details?
...
(Caused by ResponseError('too many 503 error responses'))

**Comment by wchatx** [comment]
thanks @jarigoni, I'm looking into what might be causing this

**Comment by jarigoni** [comment]
Thanks Cole. Running a test right now that pulls them one at a time…was thinking it might be a specific EntityID that was throwing things off.  It’s taking a while, but it’s working so far.

[cid:image002.png@01D5CD54.5119CD10]
John Arigoni​
Office: (720) 738-9226<tel:(303)%20916%204632>

**Comment by jarigoni** [comment]
@wchatx 

Update: Code changes pushed over the weekend appear to have helped. Data pull ran without errors this morning with entityids grouped into batches of 1000 per api call and pagesize set to 100000. 

I see there still are some pending code changes in dev. If those are part of this request, I can wait to close the issue. If not, please let me know and I will close the issue.

**Comment by wchatx** [comment]
@jarigoni thanks for the update!

I think in this case, some upstream fixes in the API itself led to resolution of the issue. I'll go ahead and close this issue but do please reach out if you come across this again.
