### ISSUE TITLE
"Verify=False" argument in DirectAccessV2 causing JSONDecodeError in V1.4.0

### ISSUE THREAD

**Issue by kiauho** [wchatx/direct-access-py#39]
In this very first call in the script:

d2 = DirectAccessV2(...
  retries = 5,
  backoff_factor=1,
  verify=False
)

JSONDecodeError is returned.

Without the 3 extra arguments (retries, backoff_factor and verify), ssl error is returned.

Please advise,

Thanks in advance.

**Comment by wchatx** [comment]
@kiauho thanks for opening this issue!

Could you add the full traceback that's returned? You can add `log_level` to the class initialization which might shed more light on what's going on. Add that output here (scrubbing any credentials or tokens) if you're able. 

```
import logging
from directaccess import DirectAccessV2
d2 = DirectAccessV2(
    client_id, 
    client_secret, 
    api_key, 
    retries=5, 
    backoff_factor=1, 
    verify=False, 
    log_level=logging.DEBUG
)
```

Also, is there anything specific about your environment that requires skipping SSL verification?

**Comment by kiauho** [comment]
Hi whatx, thanks for your quick response.  While trying to obtain the log, I notice my client_id was specified incorrectly, which causes the JSONDecodeError.  It is my bad.  The DirectAccessV2 works as expected.
Thank you.
