### ISSUE TITLE
List of possible options for `query` method?

### ISSUE THREAD

**Issue by eliasvitali** [wchatx/direct-access-py#47]
Hey there. I'm using the DirectAccess API to query for all wells in North America but I'm having trouble figuring out what the possible options for the `query` method are. From the [documentation](https://direct-access-py.readthedocs.io/en/stable/api.html#directaccessv2):

------------------------------------------------------------
`query(dataset, **options)`
* **Parameters**:  dataset – a valid dataset name. See the Direct Access documentation for valid values
* **options** – query parameters as keyword arguments

------------------------------------------------------------

What are the possible "options" or query parameters? I've seen some in the examples provided but is there a full list somewhere?

Ideally I'd like to specify a rectangular Area of Interest using North, South, East & West bounds. Is this possible? Or can I only do geographical AOIs like `county= 'reeves'`?

**Comment by desouzapalooza** [comment]
Hi @eliasvitali . You can obtain this information from the Enverus Developer API site. All of the API endpoints are listed there and you can obtain request parameters for each API endpoint. [https://app.drillinginfo.com/direct/#/api/overview](url)

**Comment by wchatx** [comment]
Thanks for the question, @eliasvitali!

@desouzapalooza is correct that the best place to find the valid query parameters (**options) is the Developer API documentation site. I'll add that it's not currently possible to supply any sort of spatial query param like a bounding box to filter your results via the API.

You can also use the **docs** method of the `DirectAccessV2` module to explore what fields are available to query for those endpoints that support it.

I've considered adding a feature that would allow filtering down API responses to those records that intersect a user-supplied geometry. It would happen client-side so there wouldn't be any speedups from this method, but you'd still end up with the output you're looking for. Would this be valuable to you? If so, could you tell me the source of the spatial data you'd like to supply (ArcGIS, QGIS, shapely, etc)?

**Comment by eliasvitali** [comment]
Thank you both for your replies. 

Currently if I am interested in a specific ROI (bounded box or circle w/ defined centre and radius) I have to request a bigger subset of data encompassing my ROI (e.g. a State/Province) and then parse through all that data using my own script. A feature like that would be neat, even without speedup I think many would benefit from it. 

Sorry I'm still new to this, what do you mean by source of the spatial data I'd supply?

**Comment by eliasvitali** [comment]
@desouzapalooza @wchatx we have recently been granted access to _global_ data as well. I couldn't find information about how I can query for global wells (for instance like the international workspace on the web app). Is the API capable of this?

**Comment by wchatx** [comment]
@eliasvitali the only international data available in the Enverus Developer API is scout articles. I believe there's a bulk delivery of international data available over the Enverus FTP site, though. Your account rep should be able to point you in the right direction.
