### ISSUE TITLE
Match `well-origins` with `well-production-values` results`

### ISSUE THREAD

**Issue by eliasvitali** [wchatx/direct-access-py#48]
I used the API to request two sets of results:

`d2.query('well-origins')` and `d2.query('well-production-details')`

I'm looking to combine the two results to essentially have a table like the one at the bottom of the web tool: 
![Screenshot from 2020-05-11 13-09-33](https://user-images.githubusercontent.com/1341505/81590403-bfbea880-9388-11ea-9d6b-6cb5c97a1eab.png)

However I'm not finding a matching ID. Well Origins has a UID for each well, while Well Production Details has the 14-digit API well number. How could I merge these?

Many thanks again!

**Comment by wchatx** [comment]
@eliasvitali I'd recommend using the well-rollups endpoint with the API14 field for this particular workflow. The table in your image is actually constructed from the well-rollups endpoint in the Enverus web app.

Let me know if that's not viable for you and I'll try a few things to see how close we can get using well-origins.

**Comment by eliasvitali** [comment]
Well rollups works well. Thanks so much for your speedy reply!

**Comment by wchatx** [comment]
Good deal!
