### ISSUE TITLE
WARNING  Throttled token request. Waiting 60 seconds...

### ISSUE THREAD

**Issue by kimgreene33** [wchatx/direct-access-py#49]
I'm failing to get a token.  The keys I am using (not shown below, I've just used dummies)  are working in other scripts that do not use the directaccess package.

from directaccess import DirectAccessV2

d2 = DirectAccessV2(
    api_key = '555555',
    client_id='5555',
    client_secret='555555555555555',
)

Output:  JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I've also tried:
 from directaccess import DirectAccessV2

d2 = DirectAccessV2(
    api_key = '<555555>',
    client_id='<5555>',
    client_secret='<555555555555555>',
)

Output:  
directaccess WARNING  Throttled token request. Waiting 60 seconds...

Is there some sort of issue with my syntax?  Do I need new keys to use direct access?

**Comment by wchatx** [comment]
Hi @kimgreene33, your first example is the correct way to provide the credentials. If you instantiate the `DirectAccessV2` class with `log_level=logging.DEBUG`, you'll likely get a more clear response from the token method as to what's going on.

Generally, a JSONDecodeError indicates that the API sent back a non-JSON response, which in this case is going to be an error message.

I also see now that providing an incorrect api_key value will return the throttled token message, whereas providing an incorrect client_id or client_secret value returns the expected error message. I'll fix this in the next release.

**Comment by kimgreene33** [comment]
Thank you for responding.  I am able to return data using V1 for rig-jobs, but continue to get authentication errors using V2 for rig-jobs.  I am hesitant to use V1 if it will be deprecated July 2020.  Is rig-jobs available on V2?

**Comment by wchatx** [comment]
@kimgreene33 yes, it's available as the `rig-analytics` endpoint in V2.

You are more than welcome to send me an email at cole.howard[at]enverus.com and we can work through any issues you're having with either this module or the API itself.
