### ISSUE TITLE
directaccess WARNING  Throttled token request. Waiting 60 seconds...

### ISSUE THREAD

**Issue by eliasvitali** [wchatx/direct-access-py#51]
Am unable to instantiate `DirectAccessV2` class. I double checked the api key, client secret & id and they are correct. I get the following error (with debug enabled):
```
urllib3.connectionpool DEBUG    https://di-api.drillinginfo.com:443 "POST /v2/direct-access/tokens?grant_type=client_credentials HTTP/1.1" 403 41
Mon, 29 Jun 2020 15:00:38 directaccess WARNING  Throttled token request. Waiting 60 seconds...
```

I am sure my credentials are correct, but this error persists 5 times before finally throwing a `DAAuthException`:

```
Traceback (most recent call last):
  File "enverus_global.py", line 24, in <module>
    d2 = login(api_key, client_id, client_secret)
  File "enverus_global.py", line 9, in login
    env = da(api_key, client_id, client_secret)
  File "/usr/local/lib/python3.6/dist-packages/directaccess/__init__.py", line 197, in __init__
    self.access_token = self.get_access_token()['access_token']
  File "/usr/local/lib/python3.6/dist-packages/directaccess/__init__.py", line 254, in get_access_token
    response.status_code, response.text)
directaccess.DAAuthException: Error getting token. Code: 403 Message: Authentication failed
```

Any insight?

**Comment by wchatx** [comment]
@eliasvitali this is either an incorrectly entered API key or there's a problem with your Enverus account that merits a support request with them.

The Enverus API returns a 400 when your client id or client secret is incorrect, and this module returns a `DAAuthException` in those cases. But the API confusingly returns a 403 both when your API key is incorrect or when you've been throttled on requesting tokens. I don't yet have a clear way to handle that case and so you see the messages you're seeing now.

**Comment by wchatx** [comment]
@eliasvitali feel free to get in touch with me at cole.howard@enverus.com if you'd like to work through these authentication issues in a private setting. Closing this issue but will reference it if I find any changes are needed to this module due to what you've reported.
