### ISSUE TITLE
How can I query specific fields of a dataset?

### ISSUE THREAD

**Issue by eliasvitali** [wchatx/direct-access-py#52]
I want to query the `producing-entities-details` dataset, but I'd like to only download records with `UpdatedDate` after or between certain dates. I can see in the [API Explorer](https://app.drillinginfo.com/direct/#/api/explorer/v2/producingEntityDetails) that one can make a request with parameters such as `btw(date1, date2)` or `gt(date)` :

UpdatedDate | No |   | Value should be in the RFC3339 format | Date the record was updated. Example: updateddate=2017-01-15 updateddate=eq(2017-01-15)
-- | -- | -- | -- | --

but I'm not sure how this translates to the `DirectAccessV2.query()` method.

**Comment by wchatx** [comment]
Hi @eliasvitali!

Here's an example:
```
client = DirectAccessV2(client_id, client_secret, api_key)
query = client.query('producing-entity-details', pagesize=100000, deleteddate='null', updateddate='btw(2020-06-01, 2020-07-28)')
```
All the "filter functions" provided by the Enverus API are passed as strings. You can also use `ge()` (greater than or equal), `gt()` (greater than), `le()` (less than or equal), `lt()` (less than), etc

**Comment by eliasvitali** [comment]
> passed as strings

This is precisely what I was looking for -- thank you!
