### ISSUE TITLE
enhancement: Completions Query

### ISSUE THREAD

**Issue by dmaupin12** [wchatx/direct-access-py#58]
I would really like to see how to pull completions to match when they were filed to the state. I can't seem to figure out how to extract the most recent w2 filings by the date they were filed (not date well was completed), if that makes sense. I'm sure i'm missing a relationship. For example, I've linked to the most recent new mexico completions table. I can pull the data if i already know the api, but unsure of how to do this without first going to the website to get the well ids. 

https://wwwapps.emnrd.state.nm.us/ocd/ocdpermitting/Reporting/Activity/WeeklyActivity.aspx

thanks!

**Comment by wchatx** [comment]
Hi @dmaupin12!

To make sure I understand, you'd like to have the completion filing date available as a field on the completions endpoint. Is that correct or have I misunderstood?

**Comment by dmaupin12** [comment]
Yes that would be perfect! This way we, could filter to the most recent completion filings. Any help would be greatly appreciated.

**Comment by wchatx** [comment]
OK, I've referred this to the appropriate folks at Enverus as an enhancement on the API. Going to close this issue out but please feel free to ping me for updates

**Comment by dmaupin12** [comment]
Appreciate it! Just as an example, i tried to use the updateddate but i'm getting over 3000 records just in the past 10 days in the well-origins table.

**Comment by dmaupin12** [comment]
Curious if you've heard back on the enhancement? Thanks!

**Comment by wchatx** [comment]
Hey @dmaupin12, I sent an email to the Developer API product owner at Enverus but don't have an update. You might want to contact their support team and make your request officially so there's a record of it.

drillinginfosupport <at> enverus.com
